package main

// generated by docsgen.py

func showHelp(cmd string) {
	s := ""
	if len(cmd) >= 6 {
		s = cmd[5 : len(cmd)-1]
	}
	switch s {
	default:
		println(`No help exists for "` + s + `".`)
	case "":
		println(`Use "help xxx" to see help for a particular subject.
Or read the Language Specification: gitlab.com/QazmoQwerty/trex/-/blob/master/docs/trex-spec.md`)
	case "example":
		println(`Use "help xxx" to see help for a particular subject.`)
	case "help":
		println(`Use "help xxx" to see help for a particular subject.`)
	case "exit":
		println(`
"exit":
Exits the interpreter. Identical to "quit".
Input: none
Parameters: none
`)
	case "quit":
		println(`
"quit":
Exits the interpreter. Identical to "exit".
Input: a list
Parameters: none
`)
	case "chars":
		println(`
"chars":
Splits a given string into a list of single characters.
Input: a string.
Parameters: none
Tip: try "example chars" to see an example.
`)
	case "count":
		println(`
"count":
Returns the number of values in a given list.
Input: a list.
Parameters: none
Tip: try "example count" to see an example.
`)
	case "len":
		println(`
"len":
Returns the length of a given string.
Input: a string.
Parameters: none
Tip: try "example len" to see an example.
`)
	case "lines":
		println(`
"lines":
Splits a given string into lines.
Input: a string.
Parameters: none
Tip: try "example lines" to see an example.
`)
	case "max":
		println(`
"max":
Finds the largest value in a list based on a specified order.
Input: a list.
Parameters: 1
* the definition by which to order the values, which must return a value 
Tip: try "example max" to see an example.
`)
	case "min":
		println(`
"min":
Finds the smallest value in a list based on a specified order.
Input: a list.
Parameters: 1
* the definition by which to order the values, which must return a value 
Tip: try "example min" to see an example.
`)
	case "numOccurs":
		println(`
"numOccurs":
Returns the number of times a value occurs inside a given list or string.
Input: a list or string.
Parameters: 1
* the value to count occurences of
Tip: try "example numOccurs" to see an example.
`)
	case "sort":
		println(`
"sort":
Sorts a list (ascending) based on a specified order.
Input: a list.
Parameters: 1
* the definition by which to order the values, which must return a value convertible to a number.
Tip: try "example sort" to see an example.
`)
	case "split":
		println(`
"split":
TODO - explanation for "split"
Input: a string.
Expected number of parameters: 1
Tip: try "example split" to see an example.
`)
	case "toLower":
		println(`
"toLower":
Returns the input with all unicode letters mapped to their lower case.
Input: a string.
Parameters: none
Tip: try "example toLower" to see an example.
`)
	case "toUpper":
		println(`
"toUpper":
Returns the input with all unicode letters mapped to their upper case.
Input: a string.
Parameters: none
Tip: try "example toUpper" to see an example.
`)
	case "unique":
		println(`
"unique":
Returns a list of all unique values in a given list.
Input: a list.
Parameters: none
Tip: try "example unique" to see an example.
`)
	case "words":
		println(`
"words":
Splits a given string into words.
Input: a string.
Parameters: none
Tip: try "example words" to see an example.
`)
	}
}

func showExample(cmd string) {
	s := ""
	if len(cmd) >= 9 {
		s = cmd[8 : len(cmd)-1]
	}
	switch s {
	default:
		println(`No example exists for "` + s + `".`)
	case "":
		println(`Try "example xxx" to see an example for a particular subject.`)
	case "example":
		println(`
--> example example
println("[Do you really need to see this?]
`)
	case "help":
		println(`
--> help example
[help for for how to use the example command]
`)
	case "quit":
		println(`
--> quit
[trex will exit]
`)
	case "exit":
		println(`
--> exit
[trex will exit]
`)
	case "chars":
		println(`
--> chars 12343
1, 2, 3, 4, 3
`)
	case "count":
		println(`
--> lines
one, two, three
--> count lines
3
`)
	case "len":
		println(`
--> len "example"
7
`)
	case "lines":
		println(`
--> []
one
two
three
--> lines
one, two, three
`)
	case "max":
		println(`
--> []
word
another
foo
--> max(#len)
another
`)
	case "min":
		println(`
--> []
word
another
foo
--> min(#len)
foo
`)
	case "numOccurs":
		println(`
--> numOccurs('fo') 'foobafo'
2
`)
	case "sort":
		println(`
--> words
one, three, four
--> sort(#len) words
one, four, three
`)
	case "split":
		println(`
--> "example?"
example?
`)
	case "toLower":
		println(`
--> toLower "Hello World"
hello world
`)
	case "toUpper":
		println(`
--> toUpper "Hello World"
HELLO WORLD
`)
	case "unique":
		println(`
--> foo => 1, 2, 3, 4, 4, 3, 2, 1, 3, 7
--> unique foo
1, 2, 3, 4, 7
`)
	case "words":
		println(`
--> foo => "this is a sentence"
--> words foo
this, is, a, sentence
`)
	}
}
